branch-defaults:
  prod:
    environment: calacademy-displays-prod
environment-defaults:
  calacademy-displays-prod:
    branch: null
    repository: null
global:
  application_name: displays.calacademy.org
  default_ec2_keyname: calacademy
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/PHP 5.6 running on
    64bit Amazon Linux/2.3.3
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
