branch-defaults:
  prod:
    environment: calacademy-displays-prod-v2
global:
  application_name: displays.calacademy.org
  default_ec2_keyname: calacademy
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
